{{- range $name, $svc := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    release: {{ $.Release.Name }}
    sidecar.istio.io/inject: "true"
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $svc.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ $svc.containerPort }}
          env:
            # 1. Load Secrets
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fitsync-secrets
                  key: jwtSecret
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: fitsync-secrets
                  key: jwtRefreshSecret
            # 2. Load DB Password (only for dev)
            {{- if $.Values.devDatabases.enabled }}
            - name: DB_PASSWORD
              value: {{ $.Values.devDatabases.auth.password | quote }}
            {{- end }}
            # 3. Load Service-Specific Envs
            {{- range $key, $val := $svc.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          
          {{- if $svc.healthCheckPath }}
          livenessProbe:
            httpGet:
              path: {{ $svc.healthCheckPath }}
              port: {{ $svc.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
          {{- end }}
{{- end }}